### PR TITLE
CHECK-277 update alegre to allow for bulk updating to generate vectors

### PR DESCRIPTION
**Pull request by DGaffney**

### CODE REVIEW

**Comment by caiosba** [comment]
@DGaffney please be sure that the new API endpoints (and/or changes to the existing ones) are documented in the `/about` endpoint.

**Comment by DGaffney** [comment]
> @DGaffney please be sure that the new API endpoints (and/or changes to the existing ones) are documented in the `/about` endpoint.

Just added an update - let me know if this is the sort of thing you were thinking would be appropriate?

**Comment by caiosba** [comment]
> > @DGaffney please be sure that the new API endpoints (and/or changes to the existing ones) are documented in the `/about` endpoint.
> 
> Just added an update - let me know if this is the sort of thing you were thinking would be appropriate?

Yes, looks good, thanks!

**Comment by DGaffney** [comment]
> > > @DGaffney please be sure that the new API endpoints (and/or changes to the existing ones) are documented in the `/about` endpoint.
> > 
> > 
> > Just added an update - let me know if this is the sort of thing you were thinking would be appropriate?
> 
> Yes, looks good, thanks!

Perfect!

**Pull request merged**
